import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  schedulelSidebar: [
    'intro',
    
    {
      type: 'category',
      label: 'Horários',
      items : [
        {
          type: 'category',
          label: 'Professores',
          items : [
            {
              type: 'autogenerated',          
              dirName: 'professor',
            },
          ]
        },
        {
          type: 'category',
          label: 'Turmas',
          items : [
            {
              type: 'autogenerated',          
              dirName: 'turma',
            },
          ]
        },
        {
          type: 'category',
          label: 'Salas',
          items : [
            {
              type: 'autogenerated',          
              dirName: 'sala',
            },
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Histórico',
      items: [
        {
          type: 'autogenerated',
          dirName: 'historico',
        }
      ]
    },
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],
  
};

export default sidebars;
